version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - mongo
    environment:
      DB_URI: "mongodb://mongo:27017"
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
